AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: React Stocks Backend - Lambda API for Tiingo and Finnhub proxying

Parameters:
  TiingoApiKey:
    Type: String
    Description: Tiingo API key for stock price data
    NoEcho: true

  FinnhubApiKey:
    Type: String
    Description: Finnhub API key for news data
    NoEcho: true

  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins (e.g., https://example.com,https://www.example.com). Use '*' for development only.
    Default: '*'

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        LOG_LEVEL: INFO
    Tracing: Active  # Enable X-Ray tracing for debugging

Resources:
  # DynamoDB Tables for Shared Caching
  StocksCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-StocksCache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticker
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: ticker
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Project
          Value: react-stocks
        - Key: CacheType
          Value: stocks

  NewsCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-NewsCache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticker
          AttributeType: S
        - AttributeName: articleHash
          AttributeType: S
      KeySchema:
        - AttributeName: ticker
          KeyType: HASH
        - AttributeName: articleHash
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Project
          Value: react-stocks
        - Key: CacheType
          Value: news

  SentimentCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-SentimentCache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticker
          AttributeType: S
        - AttributeName: articleHash
          AttributeType: S
      KeySchema:
        - AttributeName: ticker
          KeyType: HASH
        - AttributeName: articleHash
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Project
          Value: react-stocks
        - Key: CacheType
          Value: sentiment

  SentimentJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-SentimentJobs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Project
          Value: react-stocks
        - Key: CacheType
          Value: jobs

  ReactStocksApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        # CORS Configuration - Configurable via AllowedOrigins parameter
        # Security Note: Default is '*' for development convenience
        # For production, deploy with: --parameter-overrides AllowedOrigins=https://your-domain.com
        # Multiple origins: AllowedOrigins='https://prod.com,https://staging.com'
        AllowOrigins: !Split [',', !Ref AllowedOrigins]
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300
      # API Gateway Throttling - Prevents DDoS and excessive costs
      # BurstLimit: Maximum concurrent requests
      # RateLimit: Steady-state requests per second
      RouteSettings:
        'GET /stocks':
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50
        'GET /news':
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50
        'POST /sentiment':
          ThrottlingBurstLimit: 50
          ThrottlingRateLimit: 20
        'GET /sentiment':
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50
        'GET /sentiment/job/{jobId}':
          ThrottlingBurstLimit: 200
          ThrottlingRateLimit: 100
        'GET /search':
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50

  ReactStocksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/index.handler
      Description: Backend proxy for Tiingo and Finnhub APIs
      Environment:
        Variables:
          TIINGO_API_KEY: !Ref TiingoApiKey
          FINNHUB_API_KEY: !Ref FinnhubApiKey
          STOCKS_CACHE_TABLE: !Ref StocksCacheTable
          NEWS_CACHE_TABLE: !Ref NewsCacheTable
          SENTIMENT_CACHE_TABLE: !Ref SentimentCacheTable
          SENTIMENT_JOBS_TABLE: !Ref SentimentJobsTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource:
                - !GetAtt StocksCacheTable.Arn
                - !GetAtt NewsCacheTable.Arn
                - !GetAtt SentimentCacheTable.Arn
                - !GetAtt SentimentJobsTable.Arn
      Events:
        StocksApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /stocks
            Method: GET
        NewsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /news
            Method: GET
        SearchApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /search
            Method: GET
        SentimentPostApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /sentiment
            Method: POST
        SentimentGetApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /sentiment
            Method: GET
        SentimentJobApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /sentiment/job/{jobId}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShake: true
        Target: node20
        Sourcemap: false
        EntryPoints:
          - src/index.ts
        External:
          - aws-sdk
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'

Outputs:
  ReactStocksApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ReactStocksApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  ReactStocksFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ReactStocksFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  ReactStocksFunctionIamRole:
    Description: IAM Role for Lambda Function
    Value: !GetAtt ReactStocksFunctionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionRole'

  StocksCacheTableArn:
    Description: ARN of StocksCache DynamoDB table
    Value: !GetAtt StocksCacheTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-StocksCacheTableArn'

  NewsCacheTableArn:
    Description: ARN of NewsCache DynamoDB table
    Value: !GetAtt NewsCacheTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-NewsCacheTableArn'

  SentimentCacheTableArn:
    Description: ARN of SentimentCache DynamoDB table
    Value: !GetAtt SentimentCacheTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SentimentCacheTableArn'

  SentimentJobsTableArn:
    Description: ARN of SentimentJobs DynamoDB table
    Value: !GetAtt SentimentJobsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SentimentJobsTableArn'
