AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: React Stocks Backend - Lambda API for Tiingo and Polygon proxying

Parameters:
  TiingoApiKey:
    Type: String
    Description: Tiingo API key for stock price data
    NoEcho: true

  PolygonApiKey:
    Type: String
    Description: Polygon API key for news data
    NoEcho: true

  Environment:
    Type: String
    Description: Environment name (development, staging, production)
    Default: development
    AllowedValues:
      - development
      - staging
      - production

  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins (use * for development)
    Default: '*'

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        LOG_LEVEL: !If [IsProduction, ERROR, INFO]
    Tracing: Active  # Enable X-Ray tracing for debugging

Conditions:
  IsProduction: !Equals [!Ref Environment, production]
  IsDevelopment: !Equals [!Ref Environment, development]

Resources:
  ReactStocksApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      # TODO: BEFORE PRODUCTION - Wire AllowedOrigins parameter here
      # Current: Hardcoded '*' for MVP/development
      # Production: Use !Ref AllowedOrigins or !Split[',', !Ref AllowedOrigins]
      CorsConfiguration:
        AllowOrigins:
          - '*'  # TODO: Replace with !Ref AllowedOrigins in production
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  ReactStocksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/index.handler
      Description: Backend proxy for Tiingo and Polygon APIs
      Environment:
        Variables:
          TIINGO_API_KEY: !Ref TiingoApiKey
          POLYGON_API_KEY: !Ref PolygonApiKey
      Events:
        StocksApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /stocks
            Method: GET
        NewsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ReactStocksApi
            Path: /news
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: node20
        Sourcemap: false
        EntryPoints:
          - src/index.ts
        External:
          - aws-sdk

Outputs:
  ReactStocksApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ReactStocksApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  ReactStocksFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ReactStocksFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  ReactStocksFunctionIamRole:
    Description: IAM Role for Lambda Function
    Value: !GetAtt ReactStocksFunctionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionRole'
