#!/bin/bash
# Updates frontend .env file with backend API URL from SAM deployment

set -e

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Determine stack name (from argument, samconfig.toml, or default)
if [ ! -z "$1" ]; then
  # Use command-line argument if provided
  STACK_NAME="$1"
elif [ -f "samconfig.toml" ]; then
  # Parse samconfig.toml for stack_name (try deploy parameters first, then global)
  CUSTOM_STACK=$(grep -A 20 "^\[default.deploy.parameters\]" samconfig.toml | grep "^stack_name" | head -n 1 | cut -d '=' -f 2 | tr -d ' "')
  if [ ! -z "$CUSTOM_STACK" ]; then
    STACK_NAME="$CUSTOM_STACK"
  else
    # Fallback to [default.global.parameters] stack_name
    CUSTOM_STACK=$(grep -A 20 "^\[default.global.parameters\]" samconfig.toml | grep "^stack_name" | head -n 1 | cut -d '=' -f 2 | tr -d ' "')
    STACK_NAME="${CUSTOM_STACK:-react-stocks-backend}"
  fi
else
  # Default if no config found
  STACK_NAME="react-stocks-backend"
fi

echo "======================================"
echo "Updating Frontend Environment Config"
echo "======================================"
echo ""
echo "Using CloudFormation stack: $STACK_NAME"
echo ""

# Step 1: Get API URL from CloudFormation
echo "[1/3] Fetching API Gateway URL from stack: $STACK_NAME..."
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`ReactStocksApiUrl`].OutputValue' \
  --output text 2>/dev/null || echo "")

if [ -z "$API_URL" ]; then
  echo -e "${RED}✗ Error: Could not fetch API URL from CloudFormation${NC}"
  echo "  Make sure the stack '$STACK_NAME' exists and has been deployed."
  echo "  You can manually get the URL with:"
  echo "    aws cloudformation describe-stacks --stack-name $STACK_NAME"
  exit 1
fi

echo -e "${GREEN}✓ API URL: $API_URL${NC}"
echo ""

# Step 2: Check/create frontend .env file
FRONTEND_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="$FRONTEND_DIR/.env"
ENV_EXAMPLE="$FRONTEND_DIR/.env.example"

echo "[2/3] Checking frontend .env file..."

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$ENV_EXAMPLE" ]; then
    echo -e "${YELLOW}  .env not found, copying from .env.example...${NC}"
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    echo -e "${GREEN}✓ Created $ENV_FILE${NC}"
  else
    echo -e "${RED}✗ Error: .env.example not found in $FRONTEND_DIR${NC}"
    exit 1
  fi
else
  echo -e "${GREEN}✓ Found $ENV_FILE${NC}"
fi
echo ""

# Step 3: Update EXPO_PUBLIC_BACKEND_URL in .env
echo "[3/3] Updating EXPO_PUBLIC_BACKEND_URL..."

# Check if the variable already exists in the file
if grep -q "^EXPO_PUBLIC_BACKEND_URL=" "$ENV_FILE"; then
  # Update existing value
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS (BSD sed)
    sed -i '' "s|^EXPO_PUBLIC_BACKEND_URL=.*|EXPO_PUBLIC_BACKEND_URL=$API_URL|" "$ENV_FILE"
  else
    # Linux (GNU sed)
    sed -i "s|^EXPO_PUBLIC_BACKEND_URL=.*|EXPO_PUBLIC_BACKEND_URL=$API_URL|" "$ENV_FILE"
  fi
  echo -e "${GREEN}✓ Updated existing EXPO_PUBLIC_BACKEND_URL${NC}"
else
  # Add new entry
  echo "" >> "$ENV_FILE"
  echo "# Auto-generated by backend/scripts/update-env.sh" >> "$ENV_FILE"
  echo "EXPO_PUBLIC_BACKEND_URL=$API_URL" >> "$ENV_FILE"
  echo -e "${GREEN}✓ Added EXPO_PUBLIC_BACKEND_URL${NC}"
fi

echo ""
echo "======================================"
echo "Environment Update Complete!"
echo "======================================"
echo ""
echo "Frontend .env file updated at:"
echo "  $ENV_FILE"
echo ""
echo "Backend API URL set to:"
echo "  $API_URL"
echo ""
echo "You can now start the frontend with:"
echo "  npm start"
echo ""
