/**
 * Financial Domain Lexicon
 *
 * Enhances the base AFINN sentiment lexicon with financial-specific terms.
 * Scores range from -5 (very negative) to +5 (very positive).
 */

/**
 * Financial sentiment terms not covered by standard AFINN lexicon
 * These terms are common in financial news and earnings reports
 */
export const FINANCIAL_LEXICON: Record<string, number> = {
  // Positive financial terms
  bullish: 4,
  bull: 3,
  upgrade: 4,
  upgrades: 4,
  upgraded: 4,
  outperform: 4,
  outperforming: 4,
  outperforms: 4,
  beat: 3,
  beats: 3,
  exceeded: 4,
  exceeds: 4,
  exceed: 4,
  strong: 3,
  robust: 3,
  impressive: 4,
  growth: 2,
  gains: 3,
  gain: 2,
  profit: 2,
  profitable: 3,
  profitability: 2,
  margins: 1,
  synergies: 3,
  synergy: 3,
  strategic: 2,
  value: 2,
  opportunity: 2,
  opportunities: 2,
  momentum: 2,
  accelerate: 2,
  accelerating: 3,
  innovation: 2,
  innovative: 3,
  leadership: 2,
  optimistic: 3,
  confidence: 2,
  confident: 3,

  // Negative financial terms
  bearish: -4,
  bear: -3,
  downgrade: -4,
  downgrades: -4,
  downgraded: -4,
  underperform: -4,
  underperforming: -4,
  underperforms: -4,
  miss: -3,
  misses: -3,
  missed: -3,
  disappointing: -4,
  disappoints: -4,
  disappointed: -4,
  losses: -4,
  loss: -3,
  decline: -3,
  declines: -3,
  declined: -3,
  fell: -3,
  plummeted: -4,
  plummet: -4,
  plummeting: -4,
  challenges: -2,
  challenge: -2,
  challenging: -3,
  concerns: -2,
  concern: -2,
  worried: -3,
  worry: -2,
  worries: -3,
  inadequate: -3,
  mounting: -2,
  sharply: -2, // Usually negative context
  significant: 0, // Can be positive or negative, context-dependent
  regulatory: -1, // Often mentioned in negative context
  scrutiny: -2,
  litigation: -3,
  lawsuit: -3,
  debt: -2,
  volatility: -2,
  volatile: -2,
  uncertainty: -2,
  uncertain: -2,

  // Neutral but financially relevant
  earnings: 0,
  revenue: 0, // Reset to neutral, context-dependent
  announced: 0,
  reports: 0,
  reported: 0,
  quarterly: 0,
  estimates: 0,
  expectations: 0,
  guidance: 0,
  outlook: 0,
  forecast: 0,

  // Market direction terms
  surge: 4,
  surged: 4,
  rally: 3,
  rallied: 3,
  soar: 4,
  soared: 4,
  jump: 3,
  jumped: 3,
  rise: 2,
  rises: 2,
  rising: 2,
  rose: 2,
  tumble: -4,
  tumbled: -4,
  crash: -5,
  crashed: -5,
  drop: -3,
  dropped: -3,
  fall: -3,
  falling: -3,
  sink: -3,
  sinking: -3,
};
