/**
 * Cache Utility Functions
 *
 * Provides helper functions for cache management including TTL calculation,
 * freshness checks, and cache key generation.
 */

/**
 * Calculate TTL (Time To Live) for DynamoDB items
 * Returns Unix timestamp (in seconds) for when the item should expire
 *
 * @param daysFromNow - Number of days from now when item should expire
 * @returns Unix timestamp in seconds
 *
 * @example
 * const ttl = calculateTTL(7); // Expire in 7 days
 * // Returns: 1704844800 (Unix timestamp 7 days from now)
 */
export function calculateTTL(daysFromNow: number): number {
  const now = Date.now();
  const expirationMs = now + daysFromNow * 24 * 60 * 60 * 1000;
  // DynamoDB TTL expects Unix timestamp in seconds, not milliseconds
  return Math.floor(expirationMs / 1000);
}

/**
 * Check if a cached item is still fresh
 *
 * @param fetchedAt - Unix timestamp (in milliseconds) when item was fetched
 * @param maxAgeMs - Maximum age in milliseconds
 * @returns true if item is fresh, false if stale
 *
 * @example
 * const isFresh = isCacheFresh(1704758400000, 5 * 60 * 1000); // 5 minutes
 * // Returns: true if item was fetched less than 5 minutes ago
 */
export function isCacheFresh(fetchedAt: number, maxAgeMs: number): boolean {
  const now = Date.now();
  const age = now - fetchedAt;
  return age < maxAgeMs;
}

/**
 * Generate consistent cache key from ticker and date
 *
 * @param ticker - Stock ticker symbol
 * @param date - Date string in ISO format (YYYY-MM-DD)
 * @returns Consistent cache key string
 *
 * @example
 * const key = generateCacheKey('AAPL', '2025-01-15');
 * // Returns: 'AAPL#2025-01-15'
 */
export function generateCacheKey(ticker: string, date: string): string {
  return `${ticker.toUpperCase()}#${date}`;
}

/**
 * Parse cache key back into ticker and date
 *
 * @param cacheKey - Cache key generated by generateCacheKey
 * @returns Object with ticker and date
 * @throws Error if cacheKey format is invalid
 *
 * @example
 * const { ticker, date } = parseCacheKey('AAPL#2025-01-15');
 * // Returns: { ticker: 'AAPL', date: '2025-01-15' }
 */
export function parseCacheKey(cacheKey: string): { ticker: string; date: string } {
  const parts = cacheKey.split('#');

  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(`Invalid cacheKey format: expected 'TICKER#DATE', got '${cacheKey}'`);
  }

  const [ticker, date] = parts;
  return { ticker, date };
}

function normalizeDateToUTC(dateString: string): Date {
  // Parse YYYY-MM-DD as UTC midnight to avoid timezone issues
  // Split the date string and create UTC date directly
  const parts = dateString.split('-');
  const year = parseInt(parts[0], 10);
  const month = parseInt(parts[1], 10) - 1; // Month is 0-indexed
  const day = parseInt(parts[2], 10);
  return new Date(Date.UTC(year, month, day, 0, 0, 0, 0));
}

/**
 * Calculate TTL based on data type and date volatility
 */
export function calculateTTLByDataType(
  dataType: 'stock' | 'news' | 'sentiment' | 'metadata' | 'job',
  date?: string
): number {
  if (dataType === 'stock' && date) {
    try {
      const itemDate = normalizeDateToUTC(date);
      if (isNaN(itemDate.getTime())) {
         throw new Error('Invalid Date');
      }

      // Use Date.now() instead of new Date() to properly work with jest.useFakeTimers()
      const now = new Date(Date.now());
      const todayUTC = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));

      if (itemDate < todayUTC) {
        return calculateTTL(90); // Historical
      }
      return calculateTTL(1); // Current/Future
    } catch (e) {
      console.warn('Invalid date passed to calculateTTLByDataType:', date);
      return calculateTTL(1);
    }
  }

  switch (dataType) {
    case 'news': return calculateTTL(7);
    case 'sentiment': return calculateTTL(30);
    case 'metadata': return calculateTTL(30);
    case 'job': return calculateTTL(1);
    default: return calculateTTL(1);
  }
}

/**
 * Interface for cached items with TTL and fetch timestamp
 */
export interface CacheItem {
  ttl: number; // Unix timestamp in seconds
  fetchedAt: number; // Unix timestamp in milliseconds
}
