/**
 * Job Utility Functions
 *
 * Provides utilities for job ID generation and parsing for async sentiment
 * processing jobs.
 */

/**
 * Job status type definition
 */
export type JobStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';

/**
 * Generate deterministic job ID from ticker and date range
 * Same ticker and date range will always generate the same job ID
 *
 * @param ticker - Stock ticker symbol
 * @param startDate - Start date in ISO format (YYYY-MM-DD)
 * @param endDate - End date in ISO format (YYYY-MM-DD)
 * @returns Deterministic job ID string
 *
 * @example
 * const jobId = generateJobId('AAPL', '2025-01-01', '2025-01-30');
 * // Returns: 'AAPL_2025-01-01_2025-01-30'
 */
export function generateJobId(
  ticker: string,
  startDate: string,
  endDate: string
): string {
  return `${ticker.toUpperCase()}_${startDate}_${endDate}`;
}

/**
 * Parse job ID back into ticker and date range components
 *
 * @param jobId - Job ID generated by generateJobId
 * @returns Object with ticker, startDate, and endDate
 * @throws Error if job ID format is invalid
 *
 * @example
 * const { ticker, startDate, endDate } = parseJobId('AAPL_2025-01-01_2025-01-30');
 * // Returns: { ticker: 'AAPL', startDate: '2025-01-01', endDate: '2025-01-30' }
 */
export function parseJobId(jobId: string): {
  ticker: string;
  startDate: string;
  endDate: string;
} {
  const parts = jobId.split('_');

  if (parts.length !== 3) {
    throw new Error(`Invalid job ID format: ${jobId}. Expected format: TICKER_YYYY-MM-DD_YYYY-MM-DD`);
  }

  const [ticker, startDate, endDate] = parts;

  // Validate date format (basic check)
  const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  if (!dateRegex.test(startDate) || !dateRegex.test(endDate)) {
    throw new Error(`Invalid date format in job ID: ${jobId}. Dates must be YYYY-MM-DD`);
  }

  return { ticker, startDate, endDate };
}

/**
 * Validate job status value
 *
 * @param status - Status string to validate
 * @returns true if valid job status, false otherwise
 *
 * @example
 * isValidJobStatus('COMPLETED'); // Returns: true
 * isValidJobStatus('INVALID');   // Returns: false
 */
export function isValidJobStatus(status: string): status is JobStatus {
  const validStatuses: JobStatus[] = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'];
  return validStatuses.includes(status as JobStatus);
}
